<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGnxxyjz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGnxxyjz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGnxxyjz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGnxxyjz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGnxxyjz\appProdProjectContainer([
    'container.build_hash' => 'Gnxxyjz',
    'container.build_id' => '9a2d18d3',
    'container.build_time' => 1584923252,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGnxxyjz');
