<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knp_snappy.image' shared service.

$this->services['knp_snappy.image'] = $instance = new \Knp\Snappy\Image('"C:\\Programmes\\wkhtmltopdf\\bin\\wkhtmltoimage.exe"', [], []);

$instance->setLogger(${($_ = isset($this->services['monolog.logger.snappy']) ? $this->services['monolog.logger.snappy'] : $this->load('getMonolog_Logger_SnappyService.php')) && false ?: '_'});
$instance->setTemporaryFolder(($this->targetDirs[0].'/snappy'));

return $instance;
