<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHsrztn8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHsrztn8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHsrztn8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHsrztn8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHsrztn8\appDevDebugProjectContainer([
    'container.build_hash' => 'Hsrztn8',
    'container.build_id' => '3e83e127',
    'container.build_time' => 1592308500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHsrztn8');
